apiVersion: v1
kind: Service
metadata:
  name: kube-registry
  namespace: kube-system
  labels:
    app: kube-registry
spec:
  selector:
    app: kube-registry
  ports:
  - name: registry
    port: 5000
    protocol: TCP
